nome = input("Digite seu nome: ")
altura = float(input("Digite sua altura em metros: "))
peso = float(input("Digite seu peso em kg: "))
imc = peso / (altura ** 2)
peso_ideal_min = 18.5 * (altura ** 2)
peso_ideal_max = 24.9 * (altura ** 2)
print(f"Olá, {nome}!")
print(f"Seu IMC é: {imc:.2f}")
print(f"Seu peso ideal esta entre {peso_ideal_min:.2f} kg e {peso_ideal_max:.2f} kg.")